ALTER TABLE ONLINESHOP.ITEM DROP CONSTRAINT FK_ITEM_BUYER_ID
ALTER TABLE ONLINESHOP.ITEM DROP CONSTRAINT FK_ITEM_SELLER_ID
DROP TABLE ONLINESHOP.CUSTOMER CASCADE CONSTRAINTS
DROP TABLE ONLINESHOP.ITEM CASCADE CONSTRAINTS
DROP SEQUENCE ONLINESHOP.SEQ_CUSTOMER
DROP SEQUENCE ONLINESHOP.SEQ_ITEM
